export const CARDS = [
    {
      id: 0,
      name: "Red Monster",
      image: "images/project.jpg",
      type: "Fire",
      attack: "5",
      damage: "5",
      description: "A monster from the volcanic region.",
      isOpen: true,
    },
    {
      id: 1,
      name: "Pink Monster",
      image: "images/project.jpg",
      type: "Heart",
      attack: "4",
      damage: "2",
      description: "A monster from the heart region.",
      isOpen: true,
    },
    {
      id: 2,
      name: "Orange Monster",
      image: "images/project.jpg",
      type: "Mountains",
      attack: "22",
      damage: "3",
      description: "A monster from the heart region.",
      isOpen: true,
    },
    {
      id: 3,
      name: "Blue Monster",
      image: "images/project.jpg",
      type: "Water",
      attack: "1",
      damage: "13",
      description: "A monster from the water region.",
      isOpen: true,
    },
    {
      id: 4,
      name: "Green Monster",
      image: "images/project.jpg",
      type: "Grass",
      attack: "3",
      damage: "1",
      description: "A monster from the grass region.",
      isOpen: true,
    },
    {
      id: 5,
      name: "Winged Monster",
      image: "images/project.jpg",
      type: "Air",
      attack: "12",
      damage: "2",
      description: "A monster from the cloud region.",
      isOpen: true,
    },
    {
      id: 6,
      name: "Spiky Monster",
      image: "images/project.jpg",
      type: "Rock",
      attack: "4",
      damage: "6",
      description: "A monster from the mountain region.",
      isOpen: true,
    },
    {
      id: 7,
      name: "Plant Monster",
      image: "images/project.jpg",
      type: "Grass",
      attack: "8",
      damage: "4",
      description: "A monster from the jungle region.",
      isOpen: true,
    },
    {
      id: -1,
      name: "Plant Monster",
      image: "images/add.png",
      type: "Grass",
      attack: "8",
      damage: "4",
      description: "A monster from the jungle region.",
      isOpen: true,
    }

  ];
  