export const sqlQueryColumns = [
    { name: "field1" },
    { name: "field2" },
    { name: "field3" },
    { name: "field4" },
    { name: "field5" },
    { name: "field6" },
    { name: "field7" },
    { name: "field8" },
]
export const sqlQueryRows = [
    { field1: "aaaa", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "bbbb", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "cccc", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "dddd", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "eeee", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "ffff", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "gggg", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "hhhh", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "IIII", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "JJJJ", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "KKKK", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "MMMM", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "NNNN", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "OOOO", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "PPPP", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "QQQQ", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "RRRR", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "SSSS", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "TTTT", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "UUUU", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "VVVV", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "WWWW", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "XXXX", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "YYYY", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
    { field1: "ZZZZ", field2: "value2", field3: "value3", field4: "value4", field5: "value5", field6: "value6", field7: "value7", field8: "value8" },
]
export const PROJECTLIST = [
    {
        id: "id1",
        name: "Red Monster1",
        description: "A monster from the volcanic region.",
        updateTime: Date(),
    },
    {
        id: "id2",
        name: "Red Monster2",
        description: "A monster from the volcanic region.",
        updateTime: Date(),
    },
    {
        id: "id3",
        name: "Red Monster3",
        description: "A monster from the volcanic region.",
        updateTime: Date(),
    },
    {
        id: "id4",
        name: "Red Monster4",
        description: "A monster from the volcanic region.",
        updateTime: Date(),
    },
    {
        id: "id5",
        name: "Red Monster5",
        description: "A monster from the volcanic region.",
        updateTime: Date(),
    },
    {
        id: "id6",
        name: "Red Monster6",
        description: "A monster from the volcanic region.",
        updateTime: Date(),
    },
    {
        id: "id7",
        name: "Red Monster7",
        description: "A monster from the volcanic region.",
        updateTime: Date(),
    },
    {
        id: "id8",
        name: "Red Monster8",
        description: "A monster from the volcanic region.",
        updateTime: Date(),
    },
    {
        id: -1,
        name: "New Project",
        description: "New Project Creation.",
        updateTime: Date(),
    }

];
export const ObjList = [
    {
        "name": "obj1",
        "type": "table",
    },
    {
        "name": "obj2",
        "type": "table",
    },
    {
        "name": "obj3",
        "type": "table",
    },
    {
        "name": "view1",
        "type": "view",
    },
    {
        "name": "view2",
        "type": "view",
    },
    {
        "name": "view3",
        "type": "view",
    }

]
export const MetaDataList =[
    {
        "id":"obj1",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "1",
    },
    {
        "id":"obj2",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "2",
    },
    {
        "id":"obj3",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "1",
    },
    {
        "id":"view1",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "1",
    },
    {
        "id":"view2",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "1",
    },
    {
        "id":"view3",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "1",
    },
    {
        "id":"obj1",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "1",
    },
    {
        "id":"obj2",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "2",
    },
    {
        "id":"obj3",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "1",
    },
    {
        "id":"view1",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "1",
    },
    {
        "id":"view2",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "1",
    },
    {
        "id":"view3",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "1",
    },
    {
        "id":"obj1",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "1",
    },
    {
        "id":"obj2",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "2",
    },
    {
        "id":"obj3",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "1",
    },
    {
        "id":"view1",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "1",
    },
    {
        "id":"view2",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "1",
    },
    {
        "id":"view3",
        "name":"var1",
        "type": "varchar",
        "not_null": "not null",
        "dft_value": "current action",
        "cid": "1",
    }
]